### ISSUE TITLE
NIP-46 signup does not validate name presence

### ISSUE THREAD

**Issue by dtonon** [nostrband/nostrlogin.org#2]
The "Create an Account" button should be disabled until a valid name is entered.

<img width="535" alt="image" src="https://github.com/nostrband/nostrlogin.org/assets/89577423/32d7e203-a8a2-4c70-889a-40dd49137284">

<img width="526" alt="image" src="https://github.com/nostrband/nostrlogin.org/assets/89577423/d7654f15-d467-4731-850b-03ff7f58fc7d">

**Comment by nostrband** [comment]
Thanks! This should go to nostr-login repo, closing here.

**Comment by dtonon** [comment]
Oh sorry :)
